Join Tables PR
fabianofrank/hello-world-postgresql pull request #4
Opened 2022-05-06 21:27 UTC by fabianofrank

Join tables

2022-05-06 22:00 UTC, Lordkaito requested changes
Hi @fabianofrank, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 22:00 UTC, Lordkaito commented on queries.sql
> +WHERE vets.id = (SELECT id FROM vets WHERE name = 'Maisy Smith')
- [ ] I think you did a good query here but may have misunderstood the question. You are asked to check how many times an animal was seen by a vet that is not specialized in that specie. For example, if the animal is a pokemon, and the vet is specialized in digimon, that counts as one animal with a vet that is not specialized in its specie. So here you are checking for animals that were taken only by Maisy Smith, which has no specialization, but that is not exactly what you were asked. So please work on this issue.

2022-05-07 11:28 UTC, fabianofrank commented on queries.sql
> +WHERE vets.id = (SELECT id FROM vets WHERE name = 'Maisy Smith')
Yes, I understood it wrong, you are correct, thank you for the note!

2022-05-07 12:24 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @fabianofrank 👋🏻, 

Great job making the requested changes 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

![rosycheeks-mochi-peach](https://user-images.githubusercontent.com/4247740/167254265-12e8bf0b-efc2-4b1f-a72d-6f2bb41df305.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-08 03:46 UTC, merged